version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  
  supserset:
    image: amancevice/superset:latest
    ports:
      - "8088:8088"
