version: '3'

services:
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - superset

  superset:
    image: amancevice/superset:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - ./superset-logo@2x.png:/usr/local/lib/python3.6/site-packages/superset/static/assets/images/superset-logo@2x.png

  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
volumes:
  redis:
      # reference
# - https://github.com/amancevice/docker-superset/blob/master/examples/postgres/docker-compose.yml